const CATEGORIAS=[
{key:'suave',label:'🟢 SUAVE',level:0,sons:['!peido','!peido2','!peido3','!cavalo','!pare','!ui','!defuse','!plant','!chamber','!gekko','!pix','!aiqdlc']},
{key:'vip',label:'🟣 VIP',level:1,sons:['!peidofunk','!madeira','!undaia','!elegosta','!tome','!fart','!raze','!dancagatinho','!qissomeufilho','!derrame','!fah','!vineboom','!rizz','!among','!bigfa','!brbr','!calado','!brutal','!falei','!oruam','!freio','!cebolinha2','!wow2','!wow','!dexter','!nemesis','!brass','!indian','!ack','!heehee','!donald','!engracado','!gordo','!aura','!ego','!gripada','!moreno','!lavando','!obrigado','!ui2','!movie','!sentimento','!fail']},
{key:'elite',label:'🔵 ELITE',level:2,sons:['!auuu','!like','!cooked','!wnd','!rapazes','!kiko','!motivacional','!cr7','!gay','!problema','!escolhido','!cachorro','!pain','!tmp','!spider','!file','!heroi','!naosobrou','!chuva','!monark','!fart2','!pablo','!velhos','!ferrei']},
{key:'furia',label:'🟠 FÚRIA',level:3,sons:['!risada','!miauu','!bolso','!cebolinha','!grr','!lutador','!prowler','!jojo','!porra','!heart','!caganeira','!galinha','!mendigo','!ai','!tira','!longfart','!vagabunda','!tobias','!deg','!maconha','!calaboca']},
{key:'apocalipse',label:'🔴 APOCALIPSE',level:4,sons:['!tuntun','!zap','!rojao','!pou','!sigma','!copao','!susto','!dolly','!iphone','!plantao','!corinthians','!galaxy','!mensagem','!scream','!gmidao','!acorda','!vasco','!danone']}];
const status=document.getElementById('status'),grid=document.getElementById('grid'),infoToggle=document.getElementById('infoToggle'),info=document.getElementById('info'),randomButton=document.getElementById('randomButton');
const totalVisitsEl=document.getElementById('totalVisits'),onlineNowEl=document.getElementById('onlineNow'),peakOnlineEl=document.getElementById('peakOnline');
let nivelAtivo=0,tempoRestante=0,cooldownAte=0,liveOnline=false,ultimaAtualizacao=0,ultimoEstadoTimestamp=0;
function obterVisitorId(){let id=localStorage.getItem('xguiler_soundboard_visitor_id');if(!id){id=crypto.randomUUID?crypto.randomUUID():'v-'+Date.now()+'-'+Math.random().toString(36).slice(2);localStorage.setItem('xguiler_soundboard_visitor_id',id)}return id}
function atualizarStatsUI(s){if(!s)return;if(totalVisitsEl)totalVisitsEl.textContent=Number(s.total_visits||0).toLocaleString('pt-BR');if(onlineNowEl)onlineNowEl.textContent=Number(s.online||0).toLocaleString('pt-BR');if(peakOnlineEl)peakOnlineEl.textContent=Number(s.peak_online||0).toLocaleString('pt-BR')}
async function rpc(fn,body){const r=await fetch(SB_CONFIG.SUPABASE_URL+'/rest/v1/rpc/'+fn,{method:'POST',headers:{apikey:SB_CONFIG.SUPABASE_ANON_KEY,Authorization:'Bearer '+SB_CONFIG.SUPABASE_ANON_KEY,'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return r.json()}
async function registrarVisita(){try{atualizarStatsUI(await rpc('register_site_visit',{p_visitor_id:obterVisitorId()}))}catch(e){console.error(e)}}
async function heartbeat(){try{atualizarStatsUI(await rpc('heartbeat_site_visitor',{p_visitor_id:obterVisitorId()}))}catch(e){console.error(e)}}
function formatarTempo(s){if(!Number.isFinite(s)||s<=0)return '∞';s=Math.max(0,Math.floor(s));const h=Math.floor(s/3600),m=Math.floor(s%3600/60),sec=s%60;return h?String(h).padStart(2,'0')+':'+String(m).padStart(2,'0')+':'+String(sec).padStart(2,'0'):String(m).padStart(2,'0')+':'+String(sec).padStart(2,'0')}
function render(){grid.innerHTML='';CATEGORIAS.filter(c=>c.level<=nivelAtivo).forEach(c=>{const s=document.createElement('section');s.className='level';const t=document.createElement('div');t.className='level-title';t.innerHTML='<span>'+c.label+'</span><span class="level-time">~ '+formatarTempo(tempoRestante)+'</span><span class="level-cooldown '+(Date.now()<cooldownAte?'active':'ready')+'">'+(Date.now()<cooldownAte?'⏳ '+Math.ceil((cooldownAte-Date.now())/1000)+'s':'🔊 PRONTO')+'</span>';s.appendChild(t);const b=document.createElement('div');b.className='buttons';c.sons.forEach(command=>{const x=document.createElement('button');x.textContent=command;x.onclick=()=>tocar(command,x);b.appendChild(x)});s.appendChild(b);grid.appendChild(s)});grid.classList.toggle('cooldown-active',Date.now()<cooldownAte)}
async function tocar(command,button){if(Date.now()<cooldownAte)return;button.disabled=true;try{const result=await SBRealtime.sendBroadcast('broadcast',{type:'broadcast',event:'sound',payload:{command}});if(result!=='ok'){status.textContent='🔴 Erro ao enviar';status.className='status offline';button.disabled=false;return}render()}catch(e){status.textContent='🔴 Erro ao enviar';status.className='status offline';button.disabled=false;console.error('[SOUNDBOARD] Falha ao enviar:',e)}}
async function tocarRandom(){if(Date.now()<cooldownAte)return;const sons=CATEGORIAS.filter(c=>c.level<=nivelAtivo).flatMap(c=>c.sons);if(!sons.length)return;randomButton.disabled=true;const command=sons[Math.floor(Math.random()*sons.length)];try{const result=await SBRealtime.sendBroadcast('broadcast',{type:'broadcast',event:'sound',payload:{command}});if(result!=='ok'){status.textContent='🔴 Erro ao enviar';status.className='status offline'}}catch(e){status.textContent='🔴 Erro ao enviar';status.className='status offline';console.error('[SOUNDBOARD] Falha no Random:',e)}randomButton.disabled=false;render()}
function aplicarEstado(p){if(!p)return;const ts=Number(p.timestamp)||0;if(ts&&ts<ultimoEstadoTimestamp)return;if(ts)ultimoEstadoTimestamp=ts;nivelAtivo=Math.min(4,Math.max(0,Number(p.nivelAtivo)||0));tempoRestante=Math.max(0,Number(p.tempoRestante)||0);cooldownAte=Number(p.cooldownAte)||0;if(!cooldownAte&&Number(p.cooldownRestante)>0)cooldownAte=Date.now()+Number(p.cooldownRestante)*1000;ultimaAtualizacao=Date.now();liveOnline=true;status.textContent='🟢 Conectado';status.className='status online';render()}
SBRealtime.on('broadcast',p=>{if(p.event==='state')aplicarEstado(p.payload)});SBRealtime.on('status',s=>{if(s==='SUBSCRIBED'){status.textContent='🟡 Aguardando live...';status.className='status waiting';SBRealtime.sendBroadcast('broadcast',{type:'broadcast',event:'state_request',payload:{}})}else{liveOnline=false;status.textContent='🔴 Offline';status.className='status offline'}});SBRealtime.connect();
if(randomButton)randomButton.addEventListener('click',tocarRandom);if(infoToggle)infoToggle.addEventListener('click',()=>{const o=info.classList.toggle('open');infoToggle.textContent=o?'ℹ️ OCULTAR COMO FUNCIONA':'ℹ️ COMO FUNCIONA'});
setInterval(()=>{if(liveOnline&&tempoRestante>0)tempoRestante=Math.max(0,tempoRestante-1);render()},1000);setInterval(()=>{if(Date.now()-ultimaAtualizacao>12000&&liveOnline){liveOnline=false;status.textContent='🔴 Offline';status.className='status offline'}},2000);registrarVisita();heartbeat();setInterval(heartbeat,10000);render();
